# Generated by Django 5.2.7 on 2025-12-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
